ALTER TABLE doctors DROP CONSTRAINT IF EXISTS uk_doctor_user;
ALTER TABLE doctors DROP COLUMN IF EXISTS user_id;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS first_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS last_name VARCHAR(100) NOT NULL DEFAULT '';
